DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS art;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS owners;
DROP TABLE IF EXISTS transactions;
DROP VIEW IF EXISTS artist_rating;
VACUUM;